### ISSUE TITLE
Get `serde parse error` when call `block_results`

### ISSUE THREAD

**Issue by hashableric** [informalsystems/tendermint-rs#1325]
### What went wrong?

I just write simple code for get latest block result from osmosis json-rpc. 
Because the version of osmosis tendermint is v0.34, I tried compat mode `V0_34` too. It isnt changed.
When I call the `client.perform` method, the response always `serde parse error`

### Steps to reproduce

Here's core I wrote
```rust
use tendermint_rpc::{endpoint::block_results, Client, HttpClient};

#[tokio::main]
async fn main() {
    let client = HttpClient::new("https://rpc.osmosis.zone:443").unwrap();
    let result = client.perform(block_results::Request::default()).await;

    println!("{:?}", result);
}
```

I also attach v0.34 code 

```rust
use tendermint_rpc::{endpoint::block_results, Client, HttpClient, HttpClientUrl};

#[tokio::main]
async fn main() {
    let url = HttpClientUrl::try_from("https://rpc.osmosis.zone:443").unwrap();
    let client = HttpClient::builder(url)
        .compat_mode(tendermint_rpc::client::CompatMode::V0_34)
        .build()
        .unwrap();

    let result = client.perform(block_results::Request::default()).await;

    println!("{:?}", result);
}
```

Here's the `Cargo.toml`
```toml
[package]
name = "cosmrs-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmrs = { version = "0.14.0", features = ["cosmwasm", "rpc", "tokio", "grpc"] }
tokio = { version = "1.29.1", features = ["full"] }
tendermint-rpc = { version = "0.32.0", features = ["http", "tokio"] }
```

When try to execute program, I got 
```
Err(serde parse error

Caused by:
    invalid type: null, expected a string at line 1 column 196492

Location:
    /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9)
```

### Definition of "done"

Able to get `block_results` from osmosis json-rpc.
