### ISSUE TITLE
HTTP client should not try to parse body of response with non-2XX status code

### ISSUE THREAD

**Issue by xoac** [informalsystems/tendermint-rs#1359]
### What went wrong?

Concurrent request to `tx_search` fails with `value: serde parse error` 

```
    Finished dev [unoptimized + debuginfo] target(s) in 6.36s
     Running `target/debug/tendermint_tx_search`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: serde parse error

Caused by:
    expected value at line 1 column 1
```

### Steps to reproduce

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "tendermint_tx_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async 
tokio = { version = "1.13.1", features = [
    "rt-multi-thread",
    "time",
    "sync",
    "macros",
] }

# tendermint
tendermint-rpc = { version = "0.33", features = ["http-client"] }
tendermint = { version = "0.33" }
```
</details>

<details>
<summary>main.rs (not working)</summary>

```rs
use tendermint_rpc::{client::Client, query::Query, Order};

#[tokio::main]
async fn main() {
    let mut c = tendermint_rpc::client::HttpClient::new("https://juno-rpc.icycro.org").unwrap();
    c.set_compat_mode(tendermint_rpc::client::CompatMode::V0_37);

    let query = Query::default()
        .and_eq(
            "coin_spent.spender",
            "juno185zc74a7w2pfxkv6d06t3kdja65tngjgg6223x",
        )
        .and_lt("tx.height", 10_187_764);

    let query2 = Query::default()
        .and_eq(
            "coin_received.receiver",
            "juno185zc74a7w2pfxkv6d06t3kdja65tngjgg6223x",
        )
        .and_lt("tx.height", 10_187_764);

    let r_task = c.tx_search(query, false, 1, 12, tendermint_rpc::Order::Descending);
    let r2_taks = c.tx_search(query2, false, 1, 15, Order::Descending);

    let (r, r2) = tokio::try_join!(r_task, r2_taks).unwrap();

    println!("{:?}", r);
}
```

</details>

<details>
<summary>main.rs(working)</summary>

```rs
use tendermint_rpc::{client::Client, query::Query, Order};

#[tokio::main]
async fn main() {
    let mut c = tendermint_rpc::client::HttpClient::new("https://juno-rpc.icycro.org").unwrap();
    c.set_compat_mode(tendermint_rpc::client::CompatMode::V0_37);

    let query = Query::default()
        .and_eq(
            "coin_spent.spender",
            "juno185zc74a7w2pfxkv6d06t3kdja65tngjgg6223x",
        )
        .and_lt("tx.height", 10_187_764);

    let query2 = Query::default()
        .and_eq(
            "coin_received.receiver",
            "juno185zc74a7w2pfxkv6d06t3kdja65tngjgg6223x",
        )
        .and_lt("tx.height", 10_187_764);

    let r_task = c.tx_search(query, false, 1, 12, tendermint_rpc::Order::Descending);
    let r2_taks = c.tx_search(query2, false, 1, 15, Order::Descending);

    let (r, r2) = (r_task.await.unwrap(), r2_taks.await.unwrap());

    println!("{:?}", r);
}
```
</details>

<details>
<summary>diff between `not working` and `working` implementation:</summary>

```rs
    // not working main
    let (r, r2) = tokio::try_join!(r_task, r2_taks).unwrap();
    // working main
    let (r, r2) = (r_task.await.unwrap(), r2_taks.await.unwrap());
```

</details>

### Definition of "done"

concurrent calls to `HttpClient` should working without any side effects
