### ISSUE TITLE
Cannot properly parse block

### ISSUE THREAD

**Issue by rllola** [informalsystems/tendermint-rs#1403]
### What went wrong?

We are trying to use tendermint httpclient to query blocks. After a hardfork we are querying the new genesis block but have this error:

```
invalid block: last_commit is empty on non-first block
```

### Steps to reproduce

* Run Namada indexer (https://github.com/Zondax/namadexer)
* Wait for hardfork block 237907 to fail

(If needed I can provide a minimal example)

### Definition of "done"

Allowing parsing any kind of blocks regardless if they have empty commit or not.

**Comment by romac** [comment]
I just opened a [draft PR](https://github.com/informalsystems/tendermint-rs/pull/1404) with a tentative fix.

If you add the following lines at the end of [`namadexer/Cargo.toml`](https://github.com/Zondax/namadexer/blob/main/Cargo.toml) and build it again, does it solve the issue?

```toml
[patch.crates-io]
tendermint        = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "romac/allow-misformed-block" }
tendermint-rpc    = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "romac/allow-misformed-block" }
tendermint-proto  = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "romac/allow-misformed-block" }
tendermint-config = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "romac/allow-misformed-block" }
```
